### ISSUE TITLE
no_engine_registered

### ISSUE THREAD

**Issue by Prots** [boozelclark/GCM_CCS#1]
Hello, try to run and got an error:

{error,
         {{shutdown,
              {failed_to_start_child,gcm_server,
                  {bad_return_value,
                      {xml_parser,options,no_engine_registered,undefined}}}},
          {gcm_ccs_app,start,[normal,[]]}}}

Could you please check your expat version?

**Comment by boozelclark** [comment]
Hi

Unfortunately I am travelling at the moment and dont have my dev machine with me so I cant replicate the issue till later this week. I suspect that the environment variables needed for the config on your GCM server are not being set.

These need to be set in the gcm_ccs.app.src file:
        {pkg, "pkg.name.from.app"},
        {gcm_sender_id, "GCM_SENDER_ID@gcm.googleapis.com"},
        {pwd, "API_KEY"}

The can also be over-ridden in the rebar config. To confirm if this is the issue please run
application:get_env(gcm_ccs, pkg). 
application:get_env(gcm_ccs, gcm_sender_id). 
application:get_env(gcm_ccs, pwd). 

on your erlang node running gcm_ccs and see what the output is.

Thanks,

**Comment by Prots** [comment]
Hi, thanks for quick answer.
I found a solution.
Just installed expat 2.0.1 from sources, reconfigured and reinstalled exmpp.
Thanks.
